//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Banner
    {
        public int IdBanner { get; set; }
        public string Image { get; set; }
        public string UrlImage { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> StatusAktif { get; set; }
        public string Description { get; set; }
    }
}
