//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailPekerjan
    {
        public int IdDetailPekerjaan { get; set; }
        public Nullable<int> IdUserPekerjaan { get; set; }
        public Nullable<System.DateTime> PeriodeAwal { get; set; }
        public Nullable<System.DateTime> PeriodeAkhir { get; set; }
        public Nullable<decimal> NominalHasil { get; set; }
        public Nullable<decimal> TotalHasil { get; set; }
    
        public virtual UserPekerjaan UserPekerjaan { get; set; }
    }
}
