//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailKapalNelayan
    {
        public int IdKapalNelayan { get; set; }
        public Nullable<int> IdUserNelayan { get; set; }
        public Nullable<int> StatusKapal { get; set; }
        public string TypeKapal { get; set; }
        public string LokasiSandarKapal { get; set; }
        public Nullable<decimal> HasilBulanan { get; set; }
    
        public virtual UserNelayan UserNelayan { get; set; }
    }
}
