//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailUserPeternakanPerikanan
    {
        public int IdDetailPeternakan { get; set; }
        public Nullable<int> IdSatuanPendukung { get; set; }
        public string AlatBahanPendukung { get; set; }
        public Nullable<int> QuantityPendukung { get; set; }
        public Nullable<decimal> NominalPendukung { get; set; }
        public Nullable<decimal> TotalNominalPendukung { get; set; }
        public string Desc { get; set; }
        public Nullable<int> IdUserPerikanan { get; set; }
    
        public virtual MasterSatuan MasterSatuan { get; set; }
        public virtual UserPerikananPeternakan UserPerikananPeternakan { get; set; }
    }
}
