//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailAktaLahir
    {
        public int IdDetailAktaLahir { get; set; }
        public Nullable<int> IdAktaLahir { get; set; }
        public string NamaSaksi { get; set; }
        public Nullable<System.DateTime> TglLahirSaksi { get; set; }
        public string PekerjaanSaksi { get; set; }
        public string NIKSaksi { get; set; }
        public string Desc { get; set; }
    
        public virtual FormulirAktaKelahiran FormulirAktaKelahiran { get; set; }
    }
}
