//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailUserPerdagangan
    {
        public int IdDetailPerdagangan { get; set; }
        public Nullable<int> IdUserPerdagangan { get; set; }
        public Nullable<int> TypeLapak { get; set; }
        public Nullable<decimal> LuasLapak { get; set; }
        public Nullable<int> StatusLapak { get; set; }
        public string AlamatLapak { get; set; }
        public Nullable<int> JumPekerja { get; set; }
        public Nullable<decimal> SemuaBiayaBulanan { get; set; }
        public Nullable<decimal> PenghasilanBulanan { get; set; }
        public string Desc { get; set; }
    
        public virtual UserPerdagangan UserPerdagangan { get; set; }
    }
}
