//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailFlowForm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetailFlowForm()
        {
            this.StatusFormFlows = new HashSet<StatusFormFlow>();
        }
    
        public int IdDetailFlowForm { get; set; }
        public Nullable<int> IdFormFlow { get; set; }
        public Nullable<int> IdJabatan { get; set; }
        public Nullable<int> UrutanFlow { get; set; }
        public Nullable<int> SlaDetail { get; set; }
    
        public virtual MasterFlowFormulir MasterFlowFormulir { get; set; }
        public virtual MasterJabatan MasterJabatan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StatusFormFlow> StatusFormFlows { get; set; }
    }
}
