//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailForum
    {
        public int IdDetailForum { get; set; }
        public Nullable<int> IdForum { get; set; }
        public Nullable<int> IdUserRespon { get; set; }
        public string DetailRespon { get; set; }
        public string FotoDokumenRespon { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual Forum Forum { get; set; }
        public virtual User User { get; set; }
    }
}
