//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailLog
    {
        public int IdEmail { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string From { get; set; }
        public string To { get; set; }
        public string Messages { get; set; }
        public string Desc { get; set; }
        public string LinkContent { get; set; }
        public Nullable<int> StatusWA { get; set; }
    }
}
