//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FcmMessage
    {
        public int IdMessage { get; set; }
        public Nullable<int> IdUser { get; set; }
        public string Message { get; set; }
        public string Title { get; set; }
        public string Body { get; set; }
        public string Action { get; set; }
        public Nullable<int> Status { get; set; }
        public string Response { get; set; }
        public Nullable<System.DateTime> TimeStamp { get; set; }
        public Nullable<int> IdParentMessage { get; set; }
        public Nullable<int> statusWa { get; set; }
    
        public virtual User User { get; set; }
        public virtual ParentMessage ParentMessage { get; set; }
    }
}
