//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormulirKTP
    {
        public int IdFormulirKTP { get; set; }
        public Nullable<int> IdFFowForm { get; set; }
        public string TypePermohonan { get; set; }
        public string DokPendukung_ { get; set; }
        public string Desc { get; set; }
        public string LinkDocKTP { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        public virtual MasterFlowFormulir MasterFlowFormulir { get; set; }
        public virtual User User { get; set; }
    }
}
