//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Forum
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Forum()
        {
            this.DetailForums = new HashSet<DetailForum>();
        }
    
        public int IdForum { get; set; }
        public Nullable<int> IdMasterForum { get; set; }
        public Nullable<int> IdUserInsert { get; set; }
        public string DetailForum { get; set; }
        public string FotoDokumenForum { get; set; }
        public Nullable<int> HiddenUser { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailForum> DetailForums { get; set; }
        public virtual MasterForum MasterForum { get; set; }
        public virtual User User { get; set; }
    }
}
