//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterDesa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterDesa()
        {
            this.AparaturDesas = new HashSet<AparaturDesa>();
            this.Pengaduans = new HashSet<Pengaduan>();
            this.MasterFlowFormulirs = new HashSet<MasterFlowFormulir>();
        }
    
        public long IdDesa { get; set; }
        public Nullable<int> IdKecamatan { get; set; }
        public string NamaDesa { get; set; }
        public string LantitudeDesa { get; set; }
        public string LongtitudeDesa { get; set; }
        public string DescDesa { get; set; }
        public string LogoDesa { get; set; }
        public string NoKodeDesa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AparaturDesa> AparaturDesas { get; set; }
        public virtual MasterKecamatan MasterKecamatan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pengaduan> Pengaduans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterFlowFormulir> MasterFlowFormulirs { get; set; }
    }
}
