//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterFlowFormulir
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterFlowFormulir()
        {
            this.DetailFlowForms = new HashSet<DetailFlowForm>();
            this.FormulirAktaKelahirans = new HashSet<FormulirAktaKelahiran>();
            this.FormulirKTPs = new HashSet<FormulirKTP>();
        }
    
        public int IdFormFlow { get; set; }
        public Nullable<int> IdMasterForm { get; set; }
        public Nullable<int> Slaform { get; set; }
        public string DescForm { get; set; }
        public Nullable<long> IdDesa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailFlowForm> DetailFlowForms { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulirAktaKelahiran> FormulirAktaKelahirans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FormulirKTP> FormulirKTPs { get; set; }
        public virtual MasterDesa MasterDesa { get; set; }
        public virtual MasterFormulir MasterFormulir { get; set; }
    }
}
