//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterHasilBudidaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterHasilBudidaya()
        {
            this.UserPerikananPeternakans = new HashSet<UserPerikananPeternakan>();
            this.UserPertanianPerkebunans = new HashSet<UserPertanianPerkebunan>();
        }
    
        public int IdHasilBudidaya { get; set; }
        public Nullable<int> IdMasterBudidaya { get; set; }
        public string NamaHasil { get; set; }
        public Nullable<int> IdSatuanHasil { get; set; }
        public string Desc { get; set; }
    
        public virtual MasterBudidaya MasterBudidaya { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPerikananPeternakan> UserPerikananPeternakans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPertanianPerkebunan> UserPertanianPerkebunans { get; set; }
        public virtual MasterSatuan MasterSatuan { get; set; }
    }
}
