//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterKabupaten
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterKabupaten()
        {
            this.MasterKecamatans = new HashSet<MasterKecamatan>();
        }
    
        public int IdKabupaten { get; set; }
        public Nullable<int> IdPropinsi { get; set; }
        public string NamaKabupaten { get; set; }
        public string Langtitudekabupaten { get; set; }
        public string LongtitudeKabupaten { get; set; }
        public string DescKabupaten { get; set; }
        public string LogoKabupaten { get; set; }
        public string NoKodeKabupaten { get; set; }
    
        public virtual MasterPropinsi MasterPropinsi { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterKecamatan> MasterKecamatans { get; set; }
    }
}
