//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MasterBudidaya
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MasterBudidaya()
        {
            this.UserPekerjaans = new HashSet<UserPekerjaan>();
            this.MasterHasilBudidayas = new HashSet<MasterHasilBudidaya>();
        }
    
        public int IdBudidaya { get; set; }
        public Nullable<int> IdSatuanBudidaya { get; set; }
        public string NamaBudidaya { get; set; }
        public Nullable<int> IdPekerjaan { get; set; }
    
        public virtual MasterPekerjaan MasterPekerjaan { get; set; }
        public virtual MasterSatuan MasterSatuan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserPekerjaan> UserPekerjaans { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MasterHasilBudidaya> MasterHasilBudidayas { get; set; }
    }
}
