//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pengaduan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pengaduan()
        {
            this.DetailPengaduans = new HashSet<DetailPengaduan>();
        }
    
        public int IdPengaduan { get; set; }
        public Nullable<int> IdUserPengadu { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public Nullable<int> IdMasterTujuan { get; set; }
        public string PerihalPengaduan { get; set; }
        public string FotoDokumen { get; set; }
        public Nullable<System.DateTime> Timestamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPengaduan> DetailPengaduans { get; set; }
        public virtual MasterDesa MasterDesa { get; set; }
        public virtual MasterTujuanPengaduan MasterTujuanPengaduan { get; set; }
        public virtual User User { get; set; }
    }
}
