//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SiDedy_Default_v1Entities : DbContext
    {
        public SiDedy_Default_v1Entities()
            : base("name=SiDedy_Default_v1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AparaturDesa> AparaturDesas { get; set; }
        public virtual DbSet<Banner> Banners { get; set; }
        public virtual DbSet<DetailAktaLahir> DetailAktaLahirs { get; set; }
        public virtual DbSet<DetailFlowForm> DetailFlowForms { get; set; }
        public virtual DbSet<DetailFormulirKK> DetailFormulirKKs { get; set; }
        public virtual DbSet<DetailForum> DetailForums { get; set; }
        public virtual DbSet<DetailKapalNelayan> DetailKapalNelayans { get; set; }
        public virtual DbSet<DetailPekerjan> DetailPekerjans { get; set; }
        public virtual DbSet<DetailPengaduan> DetailPengaduans { get; set; }
        public virtual DbSet<DetailUserPerdagangan> DetailUserPerdagangans { get; set; }
        public virtual DbSet<DetailUserPertanian> DetailUserPertanians { get; set; }
        public virtual DbSet<DetailUserPeternakanPerikanan> DetailUserPeternakanPerikanans { get; set; }
        public virtual DbSet<EmailLog> EmailLogs { get; set; }
        public virtual DbSet<FcmMessage> FcmMessages { get; set; }
        public virtual DbSet<FormulirAktaKelahiran> FormulirAktaKelahirans { get; set; }
        public virtual DbSet<FormulirKK> FormulirKKs { get; set; }
        public virtual DbSet<FormulirKTP> FormulirKTPs { get; set; }
        public virtual DbSet<Forum> Fora { get; set; }
        public virtual DbSet<Language> Languages { get; set; }
        public virtual DbSet<MasterBudidaya> MasterBudidayas { get; set; }
        public virtual DbSet<MasterDesa> MasterDesas { get; set; }
        public virtual DbSet<MasterFlowFormulir> MasterFlowFormulirs { get; set; }
        public virtual DbSet<MasterFormulir> MasterFormulirs { get; set; }
        public virtual DbSet<MasterForum> MasterForums { get; set; }
        public virtual DbSet<MasterHasilBudidaya> MasterHasilBudidayas { get; set; }
        public virtual DbSet<MasterHubungan> MasterHubungans { get; set; }
        public virtual DbSet<MasterJabatan> MasterJabatans { get; set; }
        public virtual DbSet<MasterKabupaten> MasterKabupatens { get; set; }
        public virtual DbSet<MasterKecamatan> MasterKecamatans { get; set; }
        public virtual DbSet<MasterPekerjaan> MasterPekerjaans { get; set; }
        public virtual DbSet<MasterPropinsi> MasterPropinsis { get; set; }
        public virtual DbSet<MasterSatuan> MasterSatuans { get; set; }
        public virtual DbSet<MasterStatu> MasterStatus { get; set; }
        public virtual DbSet<MasterTujuanPengaduan> MasterTujuanPengaduans { get; set; }
        public virtual DbSet<MasterVersion> MasterVersions { get; set; }
        public virtual DbSet<ParentMessage> ParentMessages { get; set; }
        public virtual DbSet<Pengaduan> Pengaduans { get; set; }
        public virtual DbSet<RolePermission> RolePermissions { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<StatusFormFlow> StatusFormFlows { get; set; }
        public virtual DbSet<TransaksiStatu> TransaksiStatus { get; set; }
        public virtual DbSet<UserKaryawan> UserKaryawans { get; set; }
        public virtual DbSet<UserNelayan> UserNelayans { get; set; }
        public virtual DbSet<UserPekerjaan> UserPekerjaans { get; set; }
        public virtual DbSet<UserPerdagangan> UserPerdagangans { get; set; }
        public virtual DbSet<UserPerikananPeternakan> UserPerikananPeternakans { get; set; }
        public virtual DbSet<UserPermission> UserPermissions { get; set; }
        public virtual DbSet<UserPertanianPerkebunan> UserPertanianPerkebunans { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Exception> Exceptions { get; set; }
        public virtual DbSet<InfoDesa> InfoDesas { get; set; }
        public virtual DbSet<VersionInfo> VersionInfoes { get; set; }
        public virtual DbSet<VChartByAllPekerjaan> VChartByAllPekerjaans { get; set; }
        public virtual DbSet<VChartDesaByPekerjaan> VChartDesaByPekerjaans { get; set; }
        public virtual DbSet<ViewAllPenghasilan> ViewAllPenghasilans { get; set; }
        public virtual DbSet<viewAparatDesa> viewAparatDesas { get; set; }
        public virtual DbSet<ViewDetailAktaLahir> ViewDetailAktaLahirs { get; set; }
        public virtual DbSet<ViewDetailFormKK> ViewDetailFormKKs { get; set; }
        public virtual DbSet<ViewFormAktaKelahiran> ViewFormAktaKelahirans { get; set; }
        public virtual DbSet<viewFormFlow> viewFormFlows { get; set; }
        public virtual DbSet<ViewFormKK> ViewFormKKs { get; set; }
        public virtual DbSet<ViewFormKTP> ViewFormKTPs { get; set; }
        public virtual DbSet<ViewMaasterForm> ViewMaasterForms { get; set; }
        public virtual DbSet<ViewNelayan> ViewNelayans { get; set; }
        public virtual DbSet<ViewPertanian> ViewPertanians { get; set; }
        public virtual DbSet<ViewProfilUser> ViewProfilUsers { get; set; }
        public virtual DbSet<viewTransaksiFormulir> viewTransaksiFormulirs { get; set; }
        public virtual DbSet<viewTransaksiPengajuan> viewTransaksiPengajuans { get; set; }
        public virtual DbSet<ViewUserKaryawan> ViewUserKaryawans { get; set; }
        public virtual DbSet<viewUserPengajuan> viewUserPengajuans { get; set; }
        public virtual DbSet<ViewUserPerdagangan> ViewUserPerdagangans { get; set; }
        public virtual DbSet<ViewUserPeternakan> ViewUserPeternakans { get; set; }
    }
}
