//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserKaryawan
    {
        public int IdUserKaryawan { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> TypePerusahaan { get; set; }
        public string StatusKaryawan { get; set; }
        public Nullable<decimal> RatarataPenghasilan { get; set; }
        public string NamaperusahaanUsaha { get; set; }
        public string AlamatPerusahanUsaha { get; set; }
        public string Desc { get; set; }
        public Nullable<int> IdPekerjaan { get; set; }
    
        public virtual User User { get; set; }
    }
}
