//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPekerjaan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPekerjaan()
        {
            this.DetailPekerjans = new HashSet<DetailPekerjan>();
        }
    
        public int IdUserPekerjaan { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdPekerjaan { get; set; }
        public Nullable<int> IdBudidaya { get; set; }
        public Nullable<decimal> UnitPenghasilan { get; set; }
        public Nullable<int> PeriodeHasil { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailPekerjan> DetailPekerjans { get; set; }
        public virtual MasterBudidaya MasterBudidaya { get; set; }
        public virtual MasterPekerjaan MasterPekerjaan { get; set; }
        public virtual User User { get; set; }
    }
}
