//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPerdagangan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPerdagangan()
        {
            this.DetailUserPerdagangans = new HashSet<DetailUserPerdagangan>();
        }
    
        public int IdUserPerdagangan { get; set; }
        public Nullable<int> Iduser { get; set; }
        public string NamaBrandToko { get; set; }
        public string JenisDagangan { get; set; }
        public string Desc { get; set; }
        public Nullable<int> IdPekerjaan { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailUserPerdagangan> DetailUserPerdagangans { get; set; }
        public virtual User User { get; set; }
    }
}
