//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPerikananPeternakan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserPerikananPeternakan()
        {
            this.DetailUserPeternakanPerikanans = new HashSet<DetailUserPeternakanPerikanan>();
        }
    
        public int IdUserPerikanan { get; set; }
        public Nullable<int> IdUser { get; set; }
        public Nullable<int> IdHasilBudidaya { get; set; }
        public Nullable<decimal> TotalBibit { get; set; }
        public Nullable<decimal> LuasLahan { get; set; }
        public Nullable<int> JumlahPekerja { get; set; }
        public Nullable<int> PeriodePanen { get; set; }
        public Nullable<decimal> HasilPanen { get; set; }
        public Nullable<decimal> NominalHasilPanen { get; set; }
        public Nullable<int> Option1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetailUserPeternakanPerikanan> DetailUserPeternakanPerikanans { get; set; }
        public virtual MasterHasilBudidaya MasterHasilBudidaya { get; set; }
        public virtual User User { get; set; }
    }
}
