//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class VChartDesaByPekerjaan
    {
        public Nullable<long> IdNumber { get; set; }
        public Nullable<int> CountTransaksi { get; set; }
        public Nullable<decimal> TotalPenghasilan { get; set; }
        public string namadesa { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public int IdPekerjaan { get; set; }
        public string NamaPekerjaan { get; set; }
    }
}
