//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewUserPengajuan
    {
        public Nullable<long> NumberId { get; set; }
        public Nullable<long> IdNumber { get; set; }
        public Nullable<int> UserPengaju { get; set; }
        public Nullable<int> IdFormulir { get; set; }
        public string Formulir { get; set; }
        public string Dokumen { get; set; }
        public int IdTransaksiFormulir { get; set; }
    }
}
