//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFormAktaKelahiran
    {
        public Nullable<long> IdNumber { get; set; }
        public string Username { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> IdHubungan_ { get; set; }
        public string NoKTP { get; set; }
        public string NoKK { get; set; }
        public string PhoneNumber { get; set; }
        public string WaNumber { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Description { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public Nullable<int> IdUserPelapor { get; set; }
        public string NamaBayi { get; set; }
        public string KelaminBayi { get; set; }
        public string TempatKelahiran { get; set; }
        public Nullable<int> IdFormFlow { get; set; }
        public int IdFormAktaKelahiran { get; set; }
        public string HariKelahiran { get; set; }
        public Nullable<System.DateTime> TglLahir { get; set; }
        public Nullable<System.TimeSpan> WaktuKelahiran { get; set; }
        public string JenisKelahiran { get; set; }
        public Nullable<decimal> BeratBayi { get; set; }
        public Nullable<decimal> PanjangBayi { get; set; }
        public Nullable<int> AnakKe { get; set; }
        public string NamaIbu { get; set; }
        public string NikIbu { get; set; }
        public string PekerjaanIbu { get; set; }
        public Nullable<System.DateTime> TglLahirIbu { get; set; }
        public string AlamatIbu { get; set; }
        public string NamaAyah { get; set; }
        public Nullable<System.DateTime> TglLahirAyah { get; set; }
        public string PekerjaanAyah { get; set; }
        public string AlamatAyah { get; set; }
        public string NikAyah { get; set; }
        public string LinkDocAkta { get; set; }
        public string DokAkta { get; set; }
        public string NamaDesa { get; set; }
        public string NoKodeDesa { get; set; }
        public string NamaKecamatan { get; set; }
        public string KodePos { get; set; }
        public string NoKodeKecamatan { get; set; }
        public string NamaKabupaten { get; set; }
        public string DescKabupaten { get; set; }
        public string NoKodeKabupaten { get; set; }
        public string NamaPropinsi { get; set; }
        public string IbuKotaPropinsi { get; set; }
        public string NoKodePropinsi { get; set; }
        public string DescPropinsi { get; set; }
        public string NamaHubungan { get; set; }
        public string KodeHubungan { get; set; }
        public string DescHubungan { get; set; }
        public string Nomor { get; set; }
        public Nullable<int> IdMasterForm { get; set; }
    }
}
