//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewDetailFormKK
    {
        public Nullable<long> IdNumber { get; set; }
        public int IdDetailKK { get; set; }
        public Nullable<int> IdMasterHub { get; set; }
        public string NIK { get; set; }
        public string NamaLengkap { get; set; }
        public string NamaHubungan { get; set; }
        public string DescHubungan { get; set; }
        public string KodeHubungan { get; set; }
        public string AlasanPemohon { get; set; }
        public Nullable<int> JumlahKK { get; set; }
        public int IdFormulirKK { get; set; }
    }
}
