//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewFormKTP
    {
        public Nullable<long> IdNumber { get; set; }
        public int IdFormulirKTP { get; set; }
        public Nullable<int> IdFFowForm { get; set; }
        public string TypePermohonan { get; set; }
        public string DokPendukung_ { get; set; }
        public string Desc { get; set; }
        public string LinkDocKTP { get; set; }
        public string NamaHubungan { get; set; }
        public string DescHubungan { get; set; }
        public string NamaDesa { get; set; }
        public string NamaKecamatan { get; set; }
        public string NamaKabupaten { get; set; }
        public string NamaPropinsi { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public int UserId { get; set; }
        public string Address { get; set; }
        public Nullable<int> IdHubungan_ { get; set; }
        public string NoKTP { get; set; }
        public string NoKK { get; set; }
        public string PhoneNumber { get; set; }
        public string WaNumber { get; set; }
        public string UserImage { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Description { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public string Option1 { get; set; }
        public string Option2 { get; set; }
        public string Option3 { get; set; }
        public string Username { get; set; }
        public string KodePos { get; set; }
        public string NoKodeKecamatan { get; set; }
        public string NoKodeKabupaten { get; set; }
        public string NoKodePropinsi { get; set; }
        public string NoKodeDesa { get; set; }
        public string Nomor { get; set; }
        public Nullable<int> IdMasterForm { get; set; }
    }
}
