//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewProfilUser
    {
        public int UserId { get; set; }
        public string DisplayName { get; set; }
        public string Username { get; set; }
        public string Email { get; set; }
        public string Address { get; set; }
        public Nullable<int> IdHubungan_ { get; set; }
        public string NoKTP { get; set; }
        public string NoKK { get; set; }
        public string PhoneNumber { get; set; }
        public string WaNumber { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public string Pendidikan { get; set; }
        public Nullable<int> IdKecamatan { get; set; }
        public string NamaDesa { get; set; }
        public string LogoDesa { get; set; }
        public string NoKodeDesa { get; set; }
        public string NamaKecamatan { get; set; }
        public int IdKabupaten { get; set; }
        public string NoKodeKecamatan { get; set; }
        public string KodePos { get; set; }
        public string NoKodeKabupaten { get; set; }
        public Nullable<int> IdPropinsi { get; set; }
        public string NamaKabupaten { get; set; }
        public string LogoKabupaten { get; set; }
        public string NamaPropinsi { get; set; }
        public string IbuKotaPropinsi { get; set; }
        public string LogoPropinsi { get; set; }
        public string NoKodePropinsi { get; set; }
        public string UserImage { get; set; }
    }
}
