//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewAparatDesa
    {
        public Nullable<int> IdJabatan { get; set; }
        public Nullable<int> StatusAparatur { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public string DisplayName { get; set; }
        public string Username { get; set; }
        public int IdUserAparatDesa { get; set; }
        public string NamaJabatan { get; set; }
    }
}
