//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewFormFlow
    {
        public int IdFormFlow { get; set; }
        public Nullable<int> IdMasterForm { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public Nullable<int> IdJabatan { get; set; }
        public Nullable<int> UrutanFlow { get; set; }
    }
}
