//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewMaasterForm
    {
        public Nullable<long> IdNumber { get; set; }
        public int IdFormFlow { get; set; }
        public string NamaFormulir { get; set; }
        public int IdFormulir { get; set; }
        public Nullable<int> Slaform { get; set; }
        public string DescForm { get; set; }
        public string NamaDesa { get; set; }
        public string NamaKecamatan { get; set; }
        public string KodePos { get; set; }
        public string ReqForm { get; set; }
    }
}
