//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SDD.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class viewTransaksiPengajuan
    {
        public Nullable<long> IdNumber { get; set; }
        public Nullable<int> IdMasterForm { get; set; }
        public string NamaFormulir { get; set; }
        public Nullable<int> IdUserPengajuan { get; set; }
        public string NamaStatus { get; set; }
        public Nullable<int> IdStatus { get; set; }
        public Nullable<int> IdUserAparat { get; set; }
        public string AparatDesa { get; set; }
        public Nullable<int> IdJabatan { get; set; }
        public Nullable<int> StatusAparatur { get; set; }
        public Nullable<System.DateTime> PeriodeAwal { get; set; }
        public Nullable<System.DateTime> PeriodeAkhir { get; set; }
        public string NamaJabatan { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public int UserId { get; set; }
        public string Address { get; set; }
        public Nullable<int> IdHubungan_ { get; set; }
        public string NoKTP { get; set; }
        public string NoKK { get; set; }
        public string PhoneNumber { get; set; }
        public string WaNumber { get; set; }
        public string UserImage { get; set; }
        public string JenisKelamin { get; set; }
        public Nullable<System.DateTime> TanggalLahir { get; set; }
        public string Description { get; set; }
        public Nullable<long> IdDesa { get; set; }
        public string NamaDesa { get; set; }
        public int IdKecamatan { get; set; }
        public string NamaKecamatan { get; set; }
        public int IdKabupaten { get; set; }
        public string NamaKabupaten { get; set; }
        public int IdPropinsi { get; set; }
        public string NamaPropinsi { get; set; }
    }
}
